version: "2"
services:
  app:
    container_name: app
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - default


  # db:
  #   container_name: db
  #   image: postgres:9.4
  #   environment:
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: test
  #   networks:
  #     - default
  #
  # localtunnel:
  #   image: efrecon/localtunnel
  #   command: --local-host app --port 8080 --subdomain <bot name>

networks:
  default:
